/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.Test;

import java.io.FileNotFoundException;

import static org.junit.Assert.*;

public class AppTest {


    @Test
    public void linter() throws FileNotFoundException {
        String PATH = "/Users/kcmanish/Code401/java-fundamentals/linter/src/main/resources/gates.js";
        App classUnderTest = new App();
        assertEquals("Line 3: Missing semicolon.", classUnderTest.linter(PATH));
    }
}
