/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basicLibrary;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
//    @Test public void testSomeLibraryMethod() {
//        Library classUnderTest = new Library();
//        assertTrue("someLibraryMethod should return 'true'", classUnderTest.roll());
//    }


    @Test
    public void roll() {
        Library classUndertest = new Library();
//        assertArrayEquals("", classUndertest.roll(5));
//        assertArrayEquals(int[], classUndertest.roll(5));

    }

    @Test
    public void containsDuplicates() {
    }

    @Test
    public void calculateAverages() {
    }

    @Test
    public void averageOfArraysOfArrays() {
    }
}
