/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {

    Restaurant restaurant;
    Review review;

    @Before public void init() {
        restaurant = new Restaurant("Happy Teriyaki", 4, "$$");
        review = new Review("Amazing restaurant", "Manish", 5);
    }

    @Test public void restaurantToStringTest() {
        assertEquals("Restaurant{name='Happy Teriyaki', rating=4, price_category='$$'}", restaurant.toString());
    }

    @Test public void reveiewToStringTest() {
        assertEquals("Review{body='Amazing restaurant', author='Manish', rating='5'}", review.toString());
    }

    @Test public void addReviewTEst() {
        restaurant.addReview(review);
        assertEquals("Restaurant{name='Happy Teriyaki', rating=5, price_category='$$'}", restaurant.toString());
    }


}
