/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basicLibrary;

import java.util.ArrayList;
import java.util.Arrays;

public class Library {
    public static void main (String[] args) {
        int[] arr1 = new int[] {1, 2, 3, 4, 5, 5, 1};
        int[][] arrOfarr = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };

        System.out.println(Arrays.toString(roll(5)));
        System.out.println(containsDuplicates(new int[]{1,2,3,4, 5, 6,1}));
        System.out.println(containsDuplicates(new int[]{1,2,3,4, 5, 6}));
        System.out.println(calculateAverages(new int[]{1,2,3,4, 5}));
        System.out.println(averageOfArraysOfArrays(arrOfarr));


    }

    public static int[] roll(int times) {
        int[] arrayOfRolls = new int[times];
        for (int i = 0; i < times; i++) {
            arrayOfRolls[i] = (int)Math.floor((Math.random() * 6) + 1);
        }
        return arrayOfRolls;
    }

    public static boolean containsDuplicates (int[] arr) {
        for (int i = 0; i < arr.length; i++) {
            for (int j = i + 1; j < arr.length; j++) {
                if (arr[i] == arr[j]) {
                    return true;
                }
            }
        }
        return false;
    }

    public static int calculateAverages(int[] arr) {
        int sum = 0;
        for (int i = 0; i < arr.length; i++) {
            sum += arr[i];
        }
        return sum / arr.length;
    }

    public static int averageOfArraysOfArrays(int[][] arrOfArr) {
        int lowestAvg = calculateAverages(arrOfArr[0]);
        int currentAvg;

        for (int i = 1; i < arrOfArr.length; i++) {
            currentAvg = calculateAverages(arrOfArr[i]);
            if(currentAvg < lowestAvg) {
                lowestAvg = currentAvg;
            }
        }
        return lowestAvg;
    }


}
