/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basicLibrary;

public class Library {

    public static int[] roll(int times) {
        int[] arrayOfRolls = new int[times];
        for (int i = 0; i < times; i++) {
            arrayOfRolls[i] = (int)Math.floor((Math.random() * 6) + 1);
        }
        return arrayOfRolls;
    }

    public static boolean containsDuplicates (int[] arr) {
        for (int i = 0; i < arr.length; i++) {
            for (int j = i + 1; j < arr.length; j++) {
                if (arr[i] == arr[j]) {
                    return true;
                }
            }
        }
        return false;
    }

    public static int calculateAverages(int[] arr) {
        int sum = 0;
        for (int i = 0; i < arr.length; i++) {
            sum += arr[i];
        }
        return sum / arr.length;
    }

    public static int averageOfArraysOfArrays(int[][] arrOfArr) {
        int lowestAvg = calculateAverages(arrOfArr[0]);
        int currentAvg;

        for (int i = 1; i < arrOfArr.length; i++) {
            currentAvg = calculateAverages(arrOfArr[i]);
            if(currentAvg < lowestAvg) {
                lowestAvg = currentAvg;
            }
        }
        return lowestAvg;
    }


}
